# Just add or remove values to this list based on the imports you don't want : )
excluded_modules=[
    'accelerate',
    'altgraph',
    'asttokens',
    'blobfile',
    'certifi',
    'chardet',
    'charset-normalizer',
    'click',
    'colorama',
    'comm',
    'debugpy',
    'decorator',
    'docx2txt',
    'executing',
    'filelock',
    'fsspec',
    'googletrans',
    'gTTS',
    'h11',
    'h2',
    'hpack',
    'hstspreload',
    'httpcore',
    'httpx',
    'huggingface-hub',
    'hyperframe',
    'idna',
    'ipykernel',
    'ipython',
    'jedi',
    'Jinja2',
    'joblib',
    'jupyter_client',
    'jupyter_core',
    'lxml',
    'MarkupSafe',
    'matplotlib-inline',
    'mpmath',
    'nest-asyncio',
    'networkx',
    'nltk',
    'packaging',
    'parso',
    'pefile',
    'pillow',
    'platformdirs',
    'prompt_toolkit',
    'protobuf',
    'psutil',
    'pure_eval',
    'pycryptodomex',
    'pydub',
    'Pygments',
    'pygoogletranslation',
    'pyinstaller',
    'pyinstaller-hooks-contrib',
    'PyPDF2',
    'python-dateutil',
    'pywin32',
    'pywin32-ctypes',
    'PyYAML',
    'pyzmq',
    'regex',
    'requests',
    'rfc3986',
    'safetensors',
    'scipy',
    'sentencepiece',
    'setuptools',
    'simpleaudio',
    'sniffio',
    'stack-data',
    'sympy',
    'tiktoken',
    'tokenizers',
    'torch',
    'torchaudio',
    'torchvision',
    'tornado',
    'tqdm',
    'traitlets',
    'transformers',
    'typing_extensions',
    'tzdata',
    'Unidecode',
    'urllib3',
    'wcwidth',
]

append_string = ''
for mod in excluded_modules:
    append_string += f' --exclude-module {mod}'
import os

# Run the shell command with all the exclude module parameters
os.system(f'pyinstaller --windowed ".\Tiếng Việt.py" --noconfirm {append_string}')